spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vehicle
    username: root
    password: ajla020393
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true