eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8084

spring:
  application:
    name: RentaCarAPIGateway
zuul:
  host:
    max-total-connections: 10000
    max-per-route-connections: 50
  ribbon-isolation-strategy: THREAD  
  routes:
   auth-center:
      path: /login/**
      url: http://localhost:8085/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
   accounts:
      path: /account/**
      serviceId: account-ms
   orders:
      path: /order/**
      serviceId: Orders
   vehicle:
      path: /vehicl/**
      serviceId: Vehicles
  
security.jwt.secret: otherpeopledontknowit
      