eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8084

spring:
  application:
    name: RentaCarAPIGateway
zuul:
  host:
    socket-timeout-millis: 30000
  routes:
   auth-center:
      path: /login/**
      url: http://localhost:8085/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
   accounts:
      path: /account/**
      serviceId: account-ms
   orders:
      path: /orders/**
      serviceId: Orders

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
      
security.jwt.secret: otherpeopledontknowit
      